# Generated by Django 3.0.4 on 2020-03-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='owner',
        ),
    ]
