# Generated by Django 3.0.4 on 2020-03-21 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpers', '0003_auto_20200321_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='surname',
        ),
        migrations.AddField(
            model_name='helper',
            name='phonenumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='helper',
            name='user',
            field=models.ManyToManyField(default=1, to=settings.AUTH_USER_MODEL),
        ),
    ]
