# Generated by Django 3.0.4 on 2020-03-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0004_auto_20200321_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='user',
        ),
    ]
