# Generated by Django 3.0.4 on 2020-03-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0002_helper_owner'),
        ('institutions', '0003_institution_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='helpers',
            field=models.ManyToManyField(null=True, to='helpers.Helper'),
        ),
    ]
